package com.extole.reporting.rest.report.runner;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.Parameter;

import com.extole.api.report_runner.ReportRunnerExecutionContext;
import com.extole.common.lang.ToString;
import com.extole.common.rest.omissible.Omissible;
import com.extole.evaluateable.RuntimeEvaluatable;
import com.extole.reporting.rest.report.ReportTypeScope;
import com.extole.reporting.rest.report.execution.ReportFormat;

public class RefreshingReportRunnerUpdateRequest extends ReportRunnerUpdateRequest {

    private static final String JSON_EXPIRATION_MS = "expiration_ms";

    private final Omissible<Long> expirationMs;

    public RefreshingReportRunnerUpdateRequest(
        @Parameter(description = "Display name of the report runner. Has to be unique for client. " +
            "Must be present for create operation.") @JsonProperty(JSON_NAME) Omissible<String> name,
        @Parameter(
            description = "Report type name of the report runner. Must be present for create operation.") @JsonProperty(JSON_REPORT_TYPE) Omissible<
                String> reportType,
        @Parameter(description = "Optional list of formats which will get generated by the report runner, " +
            "defaults to JSON.") @JsonProperty(JSON_FORMATS) Omissible<List<ReportFormat>> formats,
        @Parameter(
            description = "List of report parameters, supported options depend on the report type.") @JsonProperty(JSON_PARAMETERS) Omissible<
                Map<String, String>> parameters,
        @Parameter(description = "Optional list of tags.") @JsonProperty(JSON_TAGS) Omissible<Set<String>> tags,
        @Parameter(
            description = "Optional list of scopes.") @JsonProperty(JSON_SCOPES) Omissible<Set<ReportTypeScope>> scopes,
        @Parameter(
            description = "Optional sftp server to which Extole has to deliver generated reports.") @JsonProperty(JSON_SFTP_SERVER_ID) Omissible<
                Optional<String>> sftpServerId,
        @JsonProperty(JSON_PAUSE_INFO) Omissible<Optional<PauseInfoRequest>> pauseInfo,
        @JsonProperty(JSON_MERGING_CONFIGURATION) Omissible<Optional<MergingConfigurationRequest>> mergingConfiguration,
        @JsonProperty(JSON_DELIVER_EMPTY_REPORTS_TO_SFTP) Omissible<Optional<Boolean>> deliverEmptyReportsToSftp,
        @Parameter(description = "Expiration duration in milliseconds, Extole will not generate new reports if " +
            "there is an existing report created within this expiration timeframe.") @JsonProperty(JSON_EXPIRATION_MS) Omissible<
                Long> expirationMs,
        @JsonProperty(JSON_REPORT_NAME_PATTERN) Omissible<
            RuntimeEvaluatable<ReportRunnerExecutionContext, String>> reportNamePattern,
        @JsonProperty(JSON_SFTP_REPORT_NAME_PATTERN) Omissible<
            RuntimeEvaluatable<ReportRunnerExecutionContext, String>> sftpReportNamePattern) {
        super(ReportRunnerType.REFRESHING, name, reportType, formats, parameters, tags, scopes, sftpServerId, pauseInfo,
            mergingConfiguration, deliverEmptyReportsToSftp, reportNamePattern, sftpReportNamePattern);
        this.expirationMs = expirationMs;
    }

    @JsonProperty(JSON_EXPIRATION_MS)
    public Omissible<Long> getExpirationMs() {
        return expirationMs;
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public String toString() {
        return ToString.create(this);
    }

    public static final class Builder extends ReportRunnerUpdateRequest.Builder<Builder> {
        private Omissible<Long> expirationMs = Omissible.omitted();

        private Builder() {
        }

        public Builder withExpirationMs(long expirationMs) {
            this.expirationMs = Omissible.of(Long.valueOf(expirationMs));
            return this;
        }

        public RefreshingReportRunnerUpdateRequest build() {
            return new RefreshingReportRunnerUpdateRequest(name, reportType, formats, parameters, tags, scopes,
                sftpServerId, pauseInfo, mergingConfiguration, deliverEmptyReportsToSftp, expirationMs,
                reportNamePattern, sftpReportNamePattern);
        }
    }
}
