package com.extole.consumer.rest.unsubscribe;

import javax.ws.rs.BeanParam;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

@Path("/v4/unsubscribe")
@Tag(name = "/v4/unsubscribe",
    description = "Endpoint meant to be used in email one-click unsubscribe" +
        " as described in https://datatracker.ietf.org/doc/html/rfc8058")
public interface UnsubscribeEndpoints {

    @Operation(summary = "Unsubscribes the email address from the specified list",
        description = "List name specifies the email list from which the unsubscribe must happen" +
            "The encrypted email is generated by the Extole platform and is unique to the email address." +
            "The encrypted email is not the email address itself." +
            "Source and other parameters are optional and are used for debugging/tracking purposes.")
    @POST
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/")
    UnsubscribeResponse unsubscribe(@BeanParam UnsubscribeRequest request) throws UnsubscribeRestException;

}
