package com.extole.reporting.rest.report;

public enum ReportParameterTypeName {
    BOOLEAN, STRING, STRING_LIST, INTEGER, DATE, DATE_RANGE, TIME, TIME_RANGE, ENUM, ENUM_LIST, CAMPAIGN_ID,
    PROGRAM_LABEL, STEPS, STEP, REGEX, LONG, CLIENT_ID, STEP_COLUMN_LIST, NORMALIZED_EMAIL, CHANNEL_MAPPING, FLOWS,
    TIERS, ROW_MAPPINGS, PERSON_MAPPINGS, FILTER_MAPPINGS, SORT_ORDER_MAPPINGS, PERSON_DIMENSION_MAPPINGS,
    METRIC_MAPPINGS, EMAIL_NAMES, GRANULAR_TIME_RANGE, CLIENT_IDS, EQUALITY, CLIENT_EVENT_METRIC_MAPPINGS,
    REWARD_EVENT_METRIC_MAPPINGS, INPUT_RECORD_ROW_MAPPINGS, REWARD_ROW_MAPPINGS, CAMPAIGN_IDS, PROGRAM_LABELS,
    INPUT_RECORD_METRIC_MAPPING, WEBHOOK_DISPATCH_ROW_MAPPINGS, WEBHOOK_DISPATCH_METRIC_MAPPING,
    AUDIENCE_MEMBERSHIPS_ROW_MAPPINGS, AUDIENCE_MEMBERSHIPS_METRIC_MAPPING, MODEL_CONFIGURATION_METRIC_MAPPING,
    REWARD_SUPPLIER_TYPES, REWARD_SUPPLIER_DISPLAY_TYPES, AUDIENCE_MEMBERS_ROW_MAPPINGS, DECIMAL, WEBHOOK_ROW_MAPPINGS,
    WEBHOOK_METRIC_MAPPING, ID, IDS, MESSAGE_SUMMARY_METRIC_MAPPINGS, SORT_ORDER_MAPPINGS_ON_STEPS, FLOW_FILTER
}
