package com.extole.client.rest.campaign.configuration;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public enum QualityRuleType {
    REFERRAL_CAP, BLACKLIST_REFERER_HEADER, SIMILAR_FRIEND_ADVOCATE_EMAIL, SELF_REFERRAL, BAD_COUNTRY, VALID_EMAIL,
    EXISTING_CUSTOMER, BOT_FILTER, BLACKLIST_DOMAIN, EVENT_SPEED, BLOCKED, RECENT_CUSTOMER,
    PREVIEW, SPAM_MESSAGE, SAME_IP, RECIPIENT_LIMIT, GLOBAL_BLOCK, SHARE_COUNT_LIMIT, PERSON_DATA, IP_FILTER,
    FRIENDS_OF_ADVOCATE_CONVERSION_LIMIT, PROFILE_DISPLACED, FRIENDS_OF_ADVOCATE_CLICK_LIMIT,
    FRIENDS_OF_ADVOCATE_REGISTRATION_LIMIT, REFERRAL_AGE, GENERIC
}
