package com.extole.client.rest.person.iss;

public enum IdentityShapeShiftType {

    ANONYMOUS_NO_KEY,
    ANONYMOUS_WITH_KEY,
    IDENTITY_WITH_KEY,
    DEVICE_NO_KEY,
    DEVICE_WITH_KEY,
    DEVICE_WITH_DIFFERENT_KEY,
    DEVICE_AND_IDENTITY_WITH_KEY,
    DEVICE_AND_IDENTITY_WITH_DIFFERENT_KEY,
    DEVICE_NO_KEY_IDENTITY_WITH_KEY,
    DEVICE_MERGED,
    DEVICE_AND_IDENTITY_MERGED,
    IDENTITY_MERGED,

}
