#!/usr/bin/env bash
set -eu
set -o pipefail
#

usage="Usage: $(basename $0) [-h] [extole_home]
    -h - help
    extole_home - extole home directory, defaults to E_HOME

Updates the java-api repo based on the latest version of extole
"

extole_home="${E_HOME:-}"

project_root=$(git rev-parse --show-toplevel)
if [ -z "$project_root" ]; then
    echo "Error: this command must be run in the java-api git repo" 1>&2
    exit 1
fi

api="$project_root/api"
mkdir -p "$api"

options=""
while [ $# -gt 0 ]; do
    case "$1" in
        -h|-\?)
            echo "$usage"
            exit 0
        ;;
        *)
            break
        ;;
    esac
    shift
done

if [ ! -z "${1:-}" ]; then
   extole_home="$1"
fi

if [ -z "${extole_home}" -o ! -d "$extole_home" ]; then
    echo "Error: extole_home not specified" 1>&2
    exit 1
fi

code_base=$extole_home/code/pluribus
if [ ! -d "$code_base" ]; then
    echo "Error: code base not found at: $code_base" 1>&2
    exit 1
fi

(
    cd $code_base
    git ls-files 'context/api/*' '*/rest/*' 'common/*' | while read -r file; do
        if [[ "$file" == *.lockfile ]]; then
            continue
        fi
        if [[ "$(basename "$file")" == "build.gradle" ]]; then
            continue
        fi
        mkdir -p "$api/$(dirname "$file")"
        cp "$file" "$api/$file"
    done
)
