package com.extole.reporting.rest.audience.operation;

public enum AudienceOperationErrorCode {
    CONFIGURATION_ERROR, COLUMN_CONFIGURATION_ERROR, INPUT_FILE_ERROR, EVENTS_EXECUTION_ERROR,
    MISMATCH_EVENTS_EXECUTION_ERROR, EXECUTION_ERROR, STORAGE_ERROR, SOFTWARE_ERROR, INTERRUPT, MEMORY_ERROR,
    UNKNOWN, ROW_COUNT_VALIDATION_RETRIES_EXHAUSTED, MEMBERS_COUNT_VALIDATION_RETRIES_EXHAUSTED
}
