package com.extole.id;

import java.security.SecureRandom;
import java.util.concurrent.TimeUnit;

public final class EpochPlusRandom implements DeprecatedIdGenerator<Long> {

    private static final long LOW_BITS = 0xffffffffL;
    private static final int HIGH_BITS = 32;
    // Thread safe
    // If contention is noticed, instances should be placed in a ThreadLocal
    // (and initialized with distinct seed values).
    private static final SecureRandom RANDOM = new SecureRandom();

    /**
     * Create a new 64-bit long identifier. The high 32-bits are the number of
     * seconds since the beginning of the Unix epoch. The low 32-bits are a
     * pseudo random number generated by a secure random number generator.
     */
    @Override
    public Long generateId() {
        return Long.valueOf(((System.currentTimeMillis() / TimeUnit.SECONDS.toMillis(1L)) << HIGH_BITS) +
            (RANDOM.nextInt() & LOW_BITS));
    }
}
